### ISSUE TITLE
bomb explode

### ISSUE THREAD

**Issue by gabbork** [20tab/Bombertab#1]
dopo che la boma esplode, prima di ridare il permesso di buttarla, bisogna aspettare un secondo (tempo che l'esplosione si consuma) altrimenti se ne lascia una con lo stesso id e crasha.

Per implementare multibomba ci serve qualcosa tipo player.bombs = ['id1','id2'...] per far saltare la bomba specifica e salvarsi gli id generati da js

alla linea 31 qualcosa del genere:

def bomb_task(bomber):
    gevent.sleep(4)
    print "EXPLODE !!!!"
    bomb = {'c':'x', 'p':bomber.id}
    for player in bomber.game.players:
        p = bomber.game.players[player]
        p.session.send('websocket', json.dumps(bomb))
        gevent.sleep(1)  #QUESTO
    bomber.dropped = False

**Comment by unbit** [comment]
It's ok, just make a pull request for the patch (WRITE IN ENGLISH)
